// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "final-project-backend/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Login provides a mock function with given fields: payload
func (_m *AuthService) Login(payload *domain.AuthPayload) *domain.Response {
	ret := _m.Called(payload)

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func(*domain.AuthPayload) *domain.Response); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

// Register provides a mock function with given fields: payload
func (_m *AuthService) Register(payload *domain.RegisterPayload) *domain.Response {
	ret := _m.Called(payload)

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func(*domain.RegisterPayload) *domain.Response); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

type mockConstructorTestingTNewAuthService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthService(t mockConstructorTestingTNewAuthService) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
