// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "final-project-backend/domain"

	mock "github.com/stretchr/testify/mock"
)

// CouponRepository is an autogenerated mock type for the CouponRepository type
type CouponRepository struct {
	mock.Mock
}

// CreateCoupon provides a mock function with given fields: coupon
func (_m *CouponRepository) CreateCoupon(coupon *domain.Coupon) *domain.Response {
	ret := _m.Called(coupon)

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func(*domain.Coupon) *domain.Response); ok {
		r0 = rf(coupon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

// DeleteCoupon provides a mock function with given fields: id
func (_m *CouponRepository) DeleteCoupon(id string) *domain.Response {
	ret := _m.Called(id)

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func(string) *domain.Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

// GetCouponOwnedByUser provides a mock function with given fields: user_id
func (_m *CouponRepository) GetCouponOwnedByUser(user_id string) *domain.Response {
	ret := _m.Called(user_id)

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func(string) *domain.Response); ok {
		r0 = rf(user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

// GetValidCoupon provides a mock function with given fields: user_id, coupon_id
func (_m *CouponRepository) GetValidCoupon(user_id string, coupon_id string) *domain.Response {
	ret := _m.Called(user_id, coupon_id)

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func(string, string) *domain.Response); ok {
		r0 = rf(user_id, coupon_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

// ReduceQty provides a mock function with given fields: user_id, coupon_id
func (_m *CouponRepository) ReduceQty(user_id string, coupon_id string) error {
	ret := _m.Called(user_id, coupon_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(user_id, coupon_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCouponRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCouponRepository creates a new instance of CouponRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCouponRepository(t mockConstructorTestingTNewCouponRepository) *CouponRepository {
	mock := &CouponRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
