// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "final-project-backend/domain"

	mock "github.com/stretchr/testify/mock"
)

// GameService is an autogenerated mock type for the GameService type
type GameService struct {
	mock.Mock
}

// CreateGame provides a mock function with given fields: game
func (_m *GameService) CreateGame(game *domain.GamePayload) *domain.Response {
	ret := _m.Called(game)

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func(*domain.GamePayload) *domain.Response); ok {
		r0 = rf(game)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

// GetAllQuestions provides a mock function with given fields:
func (_m *GameService) GetAllQuestions() *domain.Response {
	ret := _m.Called()

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func() *domain.Response); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

// GetHistoryGame provides a mock function with given fields: user_id
func (_m *GameService) GetHistoryGame(user_id string) *domain.Response {
	ret := _m.Called(user_id)

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func(string) *domain.Response); ok {
		r0 = rf(user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

// GetLeaderboards provides a mock function with given fields:
func (_m *GameService) GetLeaderboards() *domain.Response {
	ret := _m.Called()

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func() *domain.Response); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	return r0
}

type mockConstructorTestingTNewGameService interface {
	mock.TestingT
	Cleanup(func())
}

// NewGameService creates a new instance of GameService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGameService(t mockConstructorTestingTNewGameService) *GameService {
	mock := &GameService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
